export default function AboutCalculator() {
    return (
        <div className="h-screen overflow-y-auto container mx-auto px-6 py-10">
        <div className="container mx-auto px-6 py-10">
            {/* Header */}
            <h1 className="text-4xl font-bold text-center text-gray-800 mb-8">
                Cost Calculator
            </h1>

            {/* Calculator */}
            <div className="flex justify-center items-center">
                   {/* Tabs Section */}
                <div className="bg-white shadow-lg rounded-lg p-6 border border-gray-200">
                    <h2 className="text-2xl font-semibold text-gray-900 mb-4">Calculators</h2>

                    {/* WOG Cost Calculator */}
                    <div className="mb-6">
                    <div className="mb-4">
                        <p><b>Take out the guess work</b>. Built upon our repositories, estimate total building costs
                    and individual trade costs for your next contract. Estimates generated by our
                    calculator may vary by ±30% on average from actual values.</p>
                        </div>
                    </div>

                    {/* JTC Trade Cost Calculator */}
                    <div>
                    <div className="mb-4">
                    <div className="mb-2">
                    <h3 className="text-lg font-semibold"><b>What you can do with our Cost Calculator: </b></h3>
                    </div>
                        <ul className="list-disc pl-6 space-y-2">
                            <li><strong>1. WOG Cost Calculator:</strong></li>
                            <ul className="list-disc pl-6 space-y-1">
                                    <li>Estimate the dollar per sqm of each trade cost</li>
                                </ul>
                            <li><strong>2. JTC Trade Cost Calculator:</strong>
                                <ul className="list-disc pl-6 space-y-1">
                                    <li>Estimate the dollar per sqm of your total building
                                    cost based on historical data</li>
                                </ul>
                            </li>
                        </ul>
                        </div>
                        <div className="mb-2">
                        <p><strong>Facts for nerds:</strong></p> 
                        </div>
                        <div className="mb-2">
                        <p>
                        <b>Machine Learing Model :</b> Our calculators run on Tweedie Regression.
                        </p>
                        <p></p>

                        <p>
                        <i>Coming soon: more GPE data</i></p>
                        </div>

                        <p><a href="/wog_cost_calculator" className="text-blue-500 underline">Go to WOG Cost Calculator</a></p>
                        <a href="/pulse_cost_calculator" className="text-blue-500 underline">Go to JTC Trade Cost Calculator</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}
